### ISSUE TITLE
Meta: Add Support For All Map Types

### ISSUE THREAD

**Issue by dave-tucker** [aya-rs/aya#191]
Current list as of kernel 5.16

- [x]  BPF_MAP_TYPE_HASH,
- [x] 	BPF_MAP_TYPE_ARRAY,
- [x] 	BPF_MAP_TYPE_PROG_ARRAY,
- [x] 	BPF_MAP_TYPE_PERF_EVENT_ARRAY,
- [x] 	BPF_MAP_TYPE_PERCPU_HASH,
- [x] 	BPF_MAP_TYPE_PERCPU_ARRAY,
- [x] 	BPF_MAP_TYPE_STACK_TRACE,
- [ ] 	BPF_MAP_TYPE_CGROUP_ARRAY,
- [x] 	BPF_MAP_TYPE_LRU_HASH,
- [x] 	BPF_MAP_TYPE_LRU_PERCPU_HASH,
- [x] 	BPF_MAP_TYPE_LPM_TRIE,
- [ ] 	BPF_MAP_TYPE_ARRAY_OF_MAPS,
- [ ] 	BPF_MAP_TYPE_HASH_OF_MAPS,
- [ ] 	BPF_MAP_TYPE_DEVMAP,
- [x] 	BPF_MAP_TYPE_SOCKMAP,
- [ ] 	BPF_MAP_TYPE_CPUMAP,
- [ ] 	BPF_MAP_TYPE_XSKMAP,
- [x] 	BPF_MAP_TYPE_SOCKHASH,
- [ ] 	BPF_MAP_TYPE_CGROUP_STORAGE,
- [ ] 	BPF_MAP_TYPE_REUSEPORT_SOCKARRAY,
- [ ] 	BPF_MAP_TYPE_PERCPU_CGROUP_STORAGE,
- [x] 	BPF_MAP_TYPE_QUEUE,
- [x] 	BPF_MAP_TYPE_STACK,
- [ ] 	BPF_MAP_TYPE_SK_STORAGE,
- [ ] 	BPF_MAP_TYPE_DEVMAP_HASH,
- [ ] 	BPF_MAP_TYPE_STRUCT_OPS,
- [ ] 	BPF_MAP_TYPE_RINGBUF,
- [ ] 	BPF_MAP_TYPE_INODE_STORAGE,
- [ ] 	BPF_MAP_TYPE_TASK_STORAGE,
- [ ] 	BPF_MAP_TYPE_BLOOM_FILTER,

**Comment by Sherlock-Holo** [comment]
I notice in aya-bpf, lru hash map is usable, but in aya, the userspace lru hash map not exists, how do I do to use lru hash map in aya
I am using the aya 0.11 and aya-bpf is latest commit

**Comment by brevilo** [comment]
Hm, https://github.com/aya-rs/aya/issues/194, https://github.com/aya-rs/aya/issues/195 and https://github.com/aya-rs/aya/issues/199 should could be marked as done, now that #527 got merged, no?

**Comment by ajwerner** [comment]
> I notice in aya-bpf, lru hash map is usable, but in aya, the userspace lru hash map not exists, how do I do to use lru hash map in aya I am using the aya 0.11 and aya-bpf is latest commit

This was fixed in https://github.com/aya-rs/aya/pull/774.
