### ISSUE TITLE
Meta: Add Support For All BPF Program Types

### ISSUE THREAD

**Issue by dave-tucker** [aya-rs/aya#205]
- [x] BPF_PROG_TYPE_SOCKET_FILTER,
- [x] BPF_PROG_TYPE_KPROBE,
- [x] BPF_PROG_TYPE_SCHED_CLS,
- [ ] Add support for BPF_PROG_TYPE_SCHED_ACT,
- [x] BPF_PROG_TYPE_TRACEPOINT,
- [x] BPF_PROG_TYPE_XDP,
- [ ] Add support for BPF_PROG_TYPE_PERF_EVENT,
- [x] BPF_PROG_TYPE_CGROUP_SKB,
- [ ] Add support for BPF_PROG_TYPE_CGROUP_SOCK,
- [ ] Add support for BPF_PROG_TYPE_LWT_IN,
- [ ] Add support for BPF_PROG_TYPE_LWT_OUT,
- [ ] Add support for BPF_PROG_TYPE_LWT_XMIT,
- [x] BPF_PROG_TYPE_SOCK_OPS,
- [x] BPF_PROG_TYPE_SK_SKB,
- [ ] Add support for BPF_PROG_TYPE_CGROUP_DEVICE,
- [x] BPF_PROG_TYPE_SK_MSG,
- [x] BPF_PROG_TYPE_RAW_TRACEPOINT,
- [ ] Add support for BPF_PROG_TYPE_CGROUP_SOCK_ADDR,
- [ ] Add support for BPF_PROG_TYPE_LWT_SEG6LOCAL,
- [x] BPF_PROG_TYPE_LIRC_MODE2,
- [ ] Add support for BPF_PROG_TYPE_SK_REUSEPORT,
- [ ] Add support for BPF_PROG_TYPE_FLOW_DISSECTOR,
- [ ] Add support for BPF_PROG_TYPE_CGROUP_SYSCTL,
- [ ] Add support for BPF_PROG_TYPE_RAW_TRACEPOINT_WRITABLE,
- [ ] Add support for BPF_PROG_TYPE_CGROUP_SOCKOPT,
- [x] BPF_PROG_TYPE_TRACING,
- [ ] Add support for BPF_PROG_TYPE_STRUCT_OPS,
- [x] BPF_PROG_TYPE_EXT,
- [x] BPF_PROG_TYPE_LSM,
- [ ] BPF_PROG_TYPE_SK_LOOKUP,
- [ ] Add support for BPF_PROG_TYPE_SYSCALL
