### ISSUE TITLE
Convert BPF maps to using enums 

### ISSUE THREAD

**Issue by astoycos** [aya-rs/aya#386]
Following what we currenlty [do for EBPF Programs ](https://github.com/aya-rs/aya/blob/main/aya/src/programs/mod.rs#L221) convert aya's notion of bpf maps to be an Enum rather than having concrete types (HashMap, PerfEventArray etc) for every BPF map type. 

Maps were initially designed like this  to allow users to implement their own maps, however now since we implement most of the ebpf API it makes more sense to switch to enums and simply support it all.

**Comment by astoycos** [comment]
@dave-tucker You can assign me here :)

**Comment by astoycos** [comment]
I've started this in https://github.com/astoycos/aya/tree/refactor-map Still have some to go but I'll keep updating with status here

**Comment by astoycos** [comment]
This is a follow up to https://github.com/aya-rs/aya/issues/75

**Comment by astoycos** [comment]
### Work Items
- [x] Refactor API to resemble Program API 
- [x] Add `take_map` API
- [ ] Add integration testing for `take_map` API
- [] Update examples in aya-book
- [] Add example on Locking Map Refs with `take_maps`
